### ISSUE TITLE
Problem while generating garbled inputs from garbled circuits created with similar seeds 

### ISSUE THREAD

**Issue by mubeequreshi** [cryptobiu/scapi#101]
Hi,

I am implementing a garbled circuit protocol in one of my scenario, in which two parties garbled the circuits with the similar seed values, one of the party sends garbled circuit, garbled tables, translation table and his garbled input to some other machine, and the other party only sends his garbled input to that machine , and that remote machine computes the circuit based on these received values.
The problem i am facing that I do not know how I can convert my ungarbled input into garbled one ?
like I can garble the circuit, and I am also able to get garbled tables and translation table with the following code

Lets assume circuit is create with scapi circuit generation format and it works fine in my case.

`FastCircuitCreationValues values=circuit.garble(seed);`
`GarbledTablesHolder garbledTables =circuit.getGarbledTables();`
`byte[] translationTable=circuit.getTranslationTable();`
`byte[] ungarbledInput;`

**How to convert this ungarbled input into garbled one ?**

I want to do this process for the other party (let suppose it is the second one), but in case of that party I will only send the garbled input for wireIndices(2) and vice versa for party one 

I am also new to use scapi, and do not know what is the appropriate way to do this . Any help would be very appreciated.

**Comment by mubeequreshi** [comment]
I have found the answer of my question. There was a method getGarbledInputFromUngarbledInput in the FastGarbledBooleanCircuit class which I looked in the documentation. It worked for me.

**Comment by liorbiu** [comment]
@mubeequreshi the new version of scapi is developed in C++ and can be found at this [repository](https://github.com/cryptobiu/libscapi)
