### ISSUE TITLE
Improve communication layer

### ISSUE THREAD

**Issue by asafc** [cryptobiu/scapi#4]
The main goals of this improvement are:
1) A more robust channel class (re-connect on failure, timeout, etc)
2) Use ssl for secure channels
3) Enable multiple channels between the same parties using a single port.

This is currently in development by the SCAPI team.

**Comment by moriyaw** [comment]
The current master branch includes two party and multiparty communication using ssl sockets and queues.  
It also contains a native channel that is faster than the java one. 
The previous communication setup is now declared depracated.
