### ISSUE TITLE
Out-of-the-box compilation fails on Linux due to missing ActiveMQ/JMS

### ISSUE THREAD

**Issue by meilof** [cryptobiu/scapi#44]
Using the instructions from http://scapi.readthedocs.org/en/latest/install.html to compile SCAPI does not work anymore on my Fedora Core 12 Linux installation. The reason is that SCAPI seems to require ActiveMQ and JMS. I installed them, but SCAPI's build system does not find them.

In the end, I succeeded to compile SCAPI by modifying the build.xml file so that activemq-core.jar and jms.jar are listed as external dependencies, like Bouncy Castle etc.

So, is there any way to make this work out-of-the-box? At least, it would be nice to have this issue in the documentation because I had to spend quite some time to get things to work.

**Comment by AsafKleinbort** [comment]
Updated the installation instruction and several makefiles. 
Tested the installation on Ubuntu 14 and it now works.
