### ISSUE TITLE
Update example in docs for Establishing Secure Communication

### ISSUE THREAD

**Issue by irdan** [cryptobiu/scapi#57]
Right now the [docs](http://scapi.readthedocs.org/en/latest/quickstart.html#establishing-secure-communication) have an example that uses a deprecated class.  Specifically, the following warning is produced when running `scapic` on the example code.

`warning: [deprecation] CommunicationSetup in edu.biu.scapi.comm has been deprecated`

I assume this is because the communication layer (https://github.com/cryptobiu/scapi/issues/4) is currently being improved, but figured this issue would be a good reminder to update the docs.

**Comment by moriyaw** [comment]
The example was updated. 
Thanks!
