### ISSUE TITLE
Linux + Java8 installation problems: jni_md.h absence

### ISSUE THREAD

**Issue by kushti** [cryptobiu/scapi#68]
Got the problem during make:

"
...
In file included from OTExtensionMaliciousReceiver.h:2:0,
                 from OTExtensionMaliciousReceiver.cpp:1:
/usr/lib/jvm/java-8-oracle/include/jni.h:45:20: fatal error: jni_md.h: No such file or directory
 #include "jni_md.h"
"

The problem & fix is described there: http://stackoverflow.com/questions/24996017/jdk-1-8-on-linux-missing-include-file .

 Please add this to the documentation (or edit Makefile).

**Comment by AsafKleinbort** [comment]
Thanks for updating us.
Added special note about JDK 1.8 to the documentation.
