### ISSUE TITLE
ScGarbledCircuit lib missing

### ISSUE THREAD

**Issue by tpj** [cryptobiu/scapi#69]
Following the install instructions on http://scapi.readthedocs.org/en/latest/install.html for Ubuntu fails:

    Compiling the ScGarbledCircuit library...
    cp: cannot stat ‘lib/ScGarbledCircuit’: No such file or directory
    make: *** [compile-scgarbledcircuit] Error 1

It works fine if I do

    git checkout tags/SCAPI-V2-3-0

before `make`. Seems that ScGarbledCircuit has been included in the makefile in the current head of the master branch 3e56f1a477d3f8e0e94a175e8d0ce7e79656a4a1, but not added to lib.

**Comment by levymeit** [comment]
Added ScGarbledCircuit  and ScGarbledCircuit NoFixedKey as submodules.
