### ISSUE TITLE
Broken links to SDK_Pseudocode_SCAPI_V2.0.0.pdf

### ISSUE THREAD

**Issue by kushti** [cryptobiu/scapi#72]
A lot of source files contain a reference like:

'The pseudo code of this protocol can be found in Protocol 3.5 of pseudo codes document at {@link http://crypto.biu.ac.il/scapi/SDK_Pseudocode_SCAPI_V2.0.0.pdf}" 

And the link is broken

**Comment by AsafKleinbort** [comment]
fixed in 1db22301d9168951320771678c41cfdf7127efdb and ab048ddf40cac55559d86805dde04194dedc18d3
