### ISSUE TITLE
About the various OT implementations 

### ISSUE THREAD

**Issue by amittos** [cryptobiu/scapi#75]
Maybe I'm missing something but I have the following issue: 

I'm "playing" with the various OT implementations. I'm transferring **byte arrays**. The connection and the transfer works flawlessly but **how do I convert the OTROutput output back to a byte array**?

**Comment by levymeit** [comment]
I guess you are using the derived OTOnByteArrayROutput. Suppose you have an OTROutput otOutput and a byte array called p2Inputs .
To get the output byte array back just write the following.
byte[] p2Inputs = ((OTOnByteArrayROutput)otOutput).getXSigma();
