### ISSUE TITLE
Cannot use the PlainTCPChannel constructor 

### ISSUE THREAD

**Issue by amittos** [cryptobiu/scapi#76]
I get the error: 
"PlainTCPChannel is not public in edu.biu.scapi.comm.PlainTCPChannel. Cannot be accessed from outside package."

**Comment by AsafKleinbort** [comment]
Hi,
Take a look at #71.
I think it a similar case. 
Let me know if it does not help.

**Comment by amittos** [comment]
Hello, it's the same issue as the error I get is also `java.lang.ClassCastException: edu.biu.scapi.comm.twoPartyComm.PlainTCPSocketChannel cannot be cast to edu.biu.scapi.comm.PlainChannel` but I'm developing in Windows so I can't upgrade to the "bleeding edge" version. I use version 2.4 (updated 3 months ago). Any workarounds?

**Comment by AsafKleinbort** [comment]
Hi,
If you are using eclipse on windows you can build your own "bleeding edge" jar.
In any case I will try to release an updated one by the end of next week.

**Comment by amittos** [comment]
An update would be great as my IDE of choice is JetBrains IntelliJ but in the meantime I'll try Eclipse. Thank you.

**Comment by amittos** [comment]
Hello again. 

I see there's no update yet. Will it come soon? (v.2.4.0 still)
