### ISSUE TITLE
Linux: Unable to checkout during installation

### ISSUE THREAD

**Issue by kushti** [cryptobiu/scapi#77]
Please try clean installation. I'm getting following error output, and after that only making 'git clone' manually for OTExtension & MaliciousOTExtension fixes the process:

Unable to checkout 'ed1d303e9a8a0b9468311fe8a38ba295db24bd04' in submodule path 'lib/OTExtension'

**Comment by AsafKleinbort** [comment]
Thanks for letting us know. Fixed.
