### ISSUE TITLE
Malicious OT Extension multithreaded

### ISSUE THREAD

**Issue by Arash-Afshar** [cryptobiu/scapi#80]
How do I run the online phase of the OT extension in parallel? The goal is to run the initialization in the main thread, then have multiple secure computations run in parallel.

I have tried creating OTExtensionMaliciousSender and OTExtensionMaliciousReceiver and passing a thread count to them, but the program crashes when it actually wants to perform the OT.

Other than that, I do not see what else can be done, given that the transfer function ignores the channel parameter.

**Comment by amittos** [comment]
I'd like to know that as well.

**Comment by Arash-Afshar** [comment]
More info:
I also tried creating multiple OTExtensionMaliciousSender, OTExtensionMaliciousReceiver on different ports, but when it comes it performing OT online it still does not work. I suspect that the native code is using a specific port regardless.

**Comment by moriyaw** [comment]
Hi,

Sorry for the late response.

There are constructors of OTExtensionMaliciousReceiver and OTExtensionMaliciousSender that accept a parameter called "numOfThreads".
This parameter is passed to the underlying native sender and receiver.
As I understand, if the given number of threads is greater than one, the ot is done in parallel. 
Is this what you meant by "passing a thread count to them"?

Notice that in the scapi c++ implementation there is a different implementation of malicious OT, called OTExtensionBristol, that is much efficient.
In the future we will have an adapter to this native implementation in SCAPI java.

Regarding what you said about the transfer function that ignores the channel parameter - the communication in the malicious OT is done via native channel. For that reason SCAPI's channel can not be used there.

**Comment by Arash-Afshar** [comment]
Yup, if I remember correctly I passed numOfTreads and the problem was that there was not a way of instructing the underlying c++ code to use a specific thread. For example, my java code would have 3 threads and the underlying c++ code would also have 3 threads, but there was not a way saying use thread "i" of the c++ code in thread "i" of the java code....

**Comment by moriyaw** [comment]
As I understand ,the purpose of the number of threads is not to have multiple secure computations in parallel, but to have the transfer phase of the ot to be done in parallel in order to make it faster.

In order to have multiple secure computations run in parallel, the only way is to have multiple pairs of sender and receiver, as you did.
