### ISSUE TITLE
g++ 4.7 or higher needed

### ISSUE THREAD

**Issue by mahyamaftouni** [cryptobiu/scapi#83]
I'd some trouble compiling SCAPI, cause I had g++-4.6.
as there is "constructor delegation" in SCAPI source, g++-4.7 or higher is needed (although it seems uncommon to still have g++-4.6 but I think it would be helpful to mention this in your documentation).

**Comment by AsafKleinbort** [comment]
Added a comment about the g++ version .
Thanks.
