### ISSUE TITLE
Reading circuit structure only once

### ISSUE THREAD

**Issue by Arash-Afshar** [cryptobiu/scapi#84]
In the javadocs for **setGarbledTables** of **fastGarbleBooleanCircuit**, it is mentioned that this method can be used to update the garbled tables of an instance of fastGarbleBooleanCircuit. This would essentially results in reading the circuit structure only once. So, to achieve that, I performed the following but it does not work (I keep getting **IllegalArgumentException: input wire value is invalid** when evaluating the circuit).
What I did:

Garbler side:

```
inner = new ScNativeGarbledBooleanCircuit(...);
sc = new FastGarbledBooleanCircuitExtendedImp(inner, ...);

loop:
   // generate seed
   sc.setInputKeys(...);
   sc.setOutputKeys(...);
   sc.garble(seed);
   gt = sc.getGarbledTables();
   // send gt
```

Evaluator side:

```
inner = new ScNativeGarbledBooleanCircuit(...);
sc = new FastGarbledBooleanCircuitExtendedImp(inner, ...);

// obtain garbled inputs
loop:
   // receive gt
   sc.setGarbledTables(gt);
   sc.setInputs(...);
   sc.compute();
```

Is it the correct recipe? Am I missing anything?

**Comment by moriyaw** [comment]
Sorry for the late response.

Seems like you have a problem with the garbled inputs. 
If it is still relevant, do you want to send me the detailed implementation and I'll try to find the problem?

**Comment by Arash-Afshar** [comment]
Thanks for the reply but it was over a year ago ;) I don't remember how, but I fixed it somehow :)
