### ISSUE TITLE
Installation Issue on El Capitan 10.11.* with gcc49

### ISSUE THREAD

**Issue by mvenkita** [cryptobiu/scapi#87]
Even if you install gcc49 it does not use this compiler as you have the following check in the makefile

"ifneq (,$(findstring $(OSX_VERSION),10.9 10.10))"

The current El Capitan version is 10.11.\* and when you compile it goes to the default gcc compiler which is clang and fails on CRYPTOPP.

**Comment by liorbiu** [comment]
Sorry for the very late response.

I change my default compiler to gcc-4.9 using this [link](http://apple.stackexchange.com/questions/99077/how-to-set-gcc-4-8-as-default-gcc-compiler)

I got an error while compiling CryptoPP. 
CryptoPP has bug at Mac that handles with this [issue](https://github.com/weidai11/cryptopp/issues/337).
