### ISSUE TITLE
Scapi-2.4.java not found in the /usr/local/lib directory

### ISSUE THREAD

**Issue by mvenkita** [cryptobiu/scapi#89]
Your makefile does not seem to compile the main scapi jar file

$(JAR_SCAPI): $(JAR_BOUNCYCASTLE) $(JAR_APACHE_COMMONS)
  @echo "Compiling the SCAPI java code..."
  @ant
  @cp $@ assets/

**Comment by liorbiu** [comment]
Sorry for the very late response.
We had a bug that our makefile not compiling the main jar file and we fixed it.
