### ISSUE TITLE
ScGarbledCircuitNoFixedKeyJavaInterface Visual C++ solution missing

### ISSUE THREAD

**Issue by meilof** [cryptobiu/scapi#90]
I want to recompile ScGarbledCircuitNoFixedKeyJavaInterface, but it seems the Visual C++ solution to do this is mssing. Could you please add it to the repository? Or should I build it using GCC on Windows?

**Comment by moriyaw** [comment]
Hi,

Sorry for the late response.

The ScGarbledCircuitNoFixedKeyJavaInterface is on GitHub. It can be found at https://github.com/cryptobiu/ScGarbledCircuitNoFixedKey.
