### ISSUE TITLE
Exception message typo

### ISSUE THREAD

**Issue by venkatarun95** [cryptobiu/scapi#91]
In file 'src/java/edu/biu/scapi/interactiveMidProtocols/ot/otBatch/otExtension/' line 120 of commit 1c3d621b75aea14c327d40cf4d0d236b5b502483:

The exception message says "input should be an instance of OTRExtensionInput.". It should be "OTExtensionRInput".

This is a minor issue, but confused me for a while.

**Comment by moriyaw** [comment]
Fixed. 

Thank you very much for your comment.
Sorry for the late response.
