### ISSUE TITLE
Make fails on building miracl on Raspberry Pi

### ISSUE THREAD

**Issue by HasseM** [cryptobiu/scapi#92]
Following the installation instructions in the documentation, after "sudo make prefix=/usr" I end up with the following error:

```
make[1]: Entering directory '/home/pi/scapi'
Copying the miracl source files into the miracl build dir...
make[1]: Leaving directory '/home/pi/scapi'
Compiling the Miracl library (C)...
make[1]: Entering directory '/home/pi/scapi/build/Miracl'
cp 32bit/c/mirdef.h mirdef.h
gcc -fPIC -m64 -O2 -c mrcore.c
gcc: error: unrecognized command line option ‘-m64’
makefile:60: recipe for target 'mrcore.o' failed
make[1]: *** [mrcore.o] Error 1
make[1]: Leaving directory '/home/pi/scapi/build/Miracl'
makefile:142: recipe for target 'compile-miracl' failed
make: *** [compile-miracl] Error 2
pi@raspberrypi:~/scapi $
```

Obviously the -m64 commandline option is wrong. How to fix this?

**Comment by liorbiu** [comment]
Hi,

The MIracl library is one of the libraries that SCAPI use. The m64 flag is used for generate code for a 32-bit or 64-bit environment see the source [https://gcc.gnu.org/onlinedocs/gcc-4.5.3/gcc/i386-and-x86_002d64-Options.html](here).
For problem using Miracl see their page at [GitHub](https://github.com/miracl/MIRACL).

**Comment by HasseM** [comment]
The m64 flag (and also m32) is not supported on ARM (Raspberry Pi). So the build settings are wrong. The build is started from Scapi right? Not sure though if this is a mirecl problem or a scapi problem, either way the scapi build instructions fail on Arm.

I need some help getting this to work before I finally can use scapi...

**Comment by liorbiu** [comment]
SCAPI and Miracl use the m64 flag and other flags such as avx, aes-ni etc. As far as I know, these flags are not supported on ARM architecture.
Therefore I must say that currently ARM is not supported by our library.

Also, SCAPI is about to become deprecated as we are soon releasing [libscapi](https://github.com/cryptobiu/libscapi) , which is a c++ version of scapi that maintains the same API.

We are also interested to know what application you wish to develop using scapi on ARM?

**Comment by HasseM** [comment]
Well, that's a dissapointment. I was following an example that someone made about interfacing python to airmon-ng. It uses the Scapi Sniff() function for that. This runs on a cheap Rapsberry Pi board which has an Arm core. That way, I have a $35,- device that can monitor network events and alert me of problems/events. Pretty straight forward.

**Comment by liorbiu** [comment]
Scapi stands for Secure Computation API (SCAPI). Is uses strong cryptographic libraries and was originally written in Java and will be released at the end of the month in C++ language.
Maybe you want to use [Scapy](http://www.secdev.org/projects/scapy/doc/usage.html)?

**Comment by HasseM** [comment]
Yes, if only I could get it to run on my Raspberry Pi (Arm, 32 bits apps).....

**Comment by liorbiu** [comment]
**Scapi** (and **libscapi**) are **Java** and **C++** libraries.
**Scapy** is a **Python** library.
Scapi is a secure computation library.
Scapy is a networking library.
You can find the library you are looking for at: http://www.secdev.org/projects/scapy/

**Comment by HasseM** [comment]
AH! Sorry, I missed the i->y. That certainly looks interesting. Going to take a close look at it. Thanks.
