### ISSUE TITLE
Problem in making SCAPI

### ISSUE THREAD

**Issue by fatemehajikarami** [cryptobiu/scapi#93]
Hi!
i am trying to install Scapi (c++ version) on Ubuntu, after installation of prerequisites (https://scapi.readthedocs.io/en/latest/cpp_beta.html), when i wanted to make Scapi, i got this error:

make[1]: Entering directory '/home/hajikarami/libscapi/build/OTExtension'
In file included from cbitvector.cpp:8:0:
cbitvector.h:296:16: error: field ‘m_nKey’ has incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
AES_KEY_CTX m_nKey;
^
In file included from /usr/local/include/openssl/evp.h:14:0,
from ../util/typedefs.h:15,
from cbitvector.h:18,
from cbitvector.cpp:8:
/usr/local/include/openssl/ossl_typ.h:90:16: note: forward declaration of ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
typedef struct evp_cipher_ctx_st EVP_CIPHER_CTX;
^
Makefile:55: recipe for target 'util/.o' failed
make[1]: *** [util/.o] Error 1
make[1]: Leaving directory '/home/hajikarami/libscapi/build/OTExtension'
makefile:110: recipe for target 'compile-otextension' failed
make: *** [compile-otextension] Error 2

how can I solve this?

**Comment by moriyaw** [comment]
Hi, 

You are trying to install the SCAPI's c++ version.
Please connect us at https://github.com/cryptobiu/libscapi.
